apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: generic-configmap
parameters:
  - name: Name
    description: ConfigMap name
    required: true
  - name: Namespace
    description: Target namespace
    required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: ${Name}
      namespace: ${Namespace}
    data: {}
